# Site settings
title: atendemos-pc
email: lucfreelance@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página web de la aplicación de transporte privado terrestre AutoGo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lucfreelance.github.io/atendemos-pc/" # the base hostname & protocol for your site

# User setting
owner: lucfreelance
email: lucfreelance@gmail.com
facebook_username: lucfreelance
twitter_username: lucfreelance
github_username: lucfreelance
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown