# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Trozos De Realidad es una página donde destacamos algunas de las más interesantes herramientas digitales, para que las conozcas y decidas si quieres usarlas en tu día a día. Hay para todo y todos los gustos: Desde entretenimiento hasta productividad.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lucfreelance.github.io/tdrdt/" # the base hostname & protocol for your site

# User setting
owner: lucfreelance
email: lucfreelance@gmail.com
facebook_username: lucfreelance
twitter_username: lucfreelance
github_username: lucfreelance
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown